Admin::GetToolsWorker:
  cron: '0 0 * * *'

Admin::GetCorrelationWorker:
  cron: '5 0 * * *'

Admin::GetPairsWorker:
  cron: '10 0 * * *'

Admin::GetSpreadWorker:
  cron: '20 0 * * *'

Admin::TestMailWorker:
  cron: '0 3 * * *'
